#!/bin/bash
# nohup $run > lis_100 &
file_in=data
run=../a.exe

sed -i "/^10./c\10." $file_in
sleep .5
nohup $run
sleep .5
sed -i "/^10./c\15." $file_in
sleep .5
nohup $run
sleep .5
sed -i "/^15./c\20." $file_in
sleep .5
nohup $run
sleep .5
sed -i "/^20./c\25." $file_in
sleep .5
nohup $run
sleep .5
sed -i "/^25./c\30." $file_in
sleep .5
nohup $run
sleep .5
sed -i "/^30./c\35." $file_in
sleep .5
nohup $run
sleep .5
sed -i "/^35./c\40." $file_in
sleep .5
nohup $run
sleep .5
sed -i "/^40./c\45." $file_in
sleep .5
nohup $run
sleep .5
sed -i "/^45./c\50." $file_in
sleep .5
nohup $run
sleep .5
sed -i "/^50./c\55." $file_in
sleep .5
nohup $run
sleep .5
sed -i "/^55./c\60." $file_in
sleep .5
nohup $run
sleep .5
sed -i "/^60./c\65." $file_in
sleep .5
nohup $run
sed -i "/^65./c\10." $file_in