#!/bin/bash

cd RESCALE0_P
../a.out
cat error
cd ../RESCALE0_S
../a.out
cat error
cd ../RESCALE1_P
../a.out
cat error
cd ../RESCALE1_S
../a.out
cat error
cd RESCALE2_P
../a.out
cat error
cd ../RESCALE2_S
../a.out
cat error
cd ../RESCALE3_P
../a.out
cat error
cd ../RESCALE3_S
../a.out
cat error
cd RESCALE4_P
../a.out
cat error
cd ../RESCALE4_S
../a.out
cat error
cd ../RESCALE5_P
../a.out
cat error
cd ../RESCALE5_S
